[pytest]
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning:evidently.*
    ignore::DeprecationWarning:litestar.*
    ignore::litestar.utils.deprecation.LitestarDeprecationWarning
    ignore::DeprecationWarning:dash.*
